{% set version = '0.0-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-frab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/frab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/frab/frab_{{ version }}.tar.gz
  sha256: ac749f212838ccfde89d468ec09b95ba02db935965972ec97caea390158ba7f0

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0_7
    - r-disordr >=0.9_8_2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0_7
    - r-disordr >=0.9_8_2

test:
  commands:
    - $R -e "library('frab')"           # [not win]
    - "\"%R%\" -e \"library('frab')\""  # [win]

about:
  home: https://github.com/RobinHankin/frab
  license: GPL-2.0-or-later
  summary: Methods to "add" two R tables; also an alternative interpretation of named vectors
    as generalized R tables, so that c(a=1,b=2,c=3) + c(b=3,a=-1) will return c(b=5,c=3).  Uses
    'disordR' discipline (Hankin, 2022, <doi:10.48550/arXiv.2210.03856>).  Extraction
    and replacement methods are provided.  The underlying mathematical structure is
    the Free Abelian group, hence the name.  To cite in publications please use Hankin
    (2023) <doi:10.48550/arXiv.2307.13184>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
